### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by PLUCS2** [ColtW27/Whilom-Halls#6]
- [x] Get rid of the banner up at the top 
- [x] Change the footer so that instead of dead links it has information about you or your social media links 
- [x] Keep header as scrolling down splash page 
- [x] Add images to the splash page once you set up AWS 
- [x] Switch login and sign up - sign up should be in the white bubble 
- [x] Your cursor should change when you hover over the links in the header 
- [ ] Add error messages to forms 
- [x]  Fix logout button 

Excellent job so far! :)

**Comment by ColtW27** [comment]
I'm not sure what you mean about fixing logout button, I have to redo the entire dropdown so that it is react and on click. So it will be styled then. No luck with errors. I'm going to start on Aws presently.
